apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: util
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: gcr.io/qmit-pro/api-gateway:latest
          imagePullPolicy: Always
          name: server
          resources: {}
          env:
            - name: QMIT_APP_ENV
              value: prod
            - name: QMIT_CLUSTER_NAME
              value: prod
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: util
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: api-gateway
  name: api-gateway
  namespace: util
spec:
  rules:
    - host: api.qmit.pro
      http:
        paths:
          - backend:
              serviceName: api-gateway
              servicePort: 80
            path: /
  tls:
    - hosts:
        - api.qmit.pro
      secretName: api-qmit-pro-cert
